# Copyright (c) 2026 Douglas P. Kingston III. MIT License - see LICENSE.
"""
Remote config fetcher for Beagle nodes.

Allows a node to be provisioned with only a minimal bootstrap.yaml (server URL,
node_id, node_secret) and fetch its full operating config from the server at
startup, polling for updates in the background.

Bootstrap flow
--------------
1. Operator runs: manage_nodes.py add <node_id> --lat ... --lon ...
   This creates the node record in the server DB and prints a secret.
2. Operator writes /etc/beagle/bootstrap.yaml (or wherever) with that secret.
3. Node starts with: beagle-node --bootstrap /etc/beagle/bootstrap.yaml
4. RemoteConfigFetcher registers with the server and downloads NodeConfig.
5. If the server is unreachable, the last cached config is used (if available).
6. A background thread long-polls for updates; hot-reloadable fields are
   applied immediately.  Fields that require a restart are logged as warnings.

Config cache
------------
The fetched config is written to ``config_cache_path`` as JSON.  On the next
startup, if the server is unreachable, this cached copy allows the node to
start without a network connection.
"""

from __future__ import annotations

import json
import logging
import random
import threading
import time
from pathlib import Path
from typing import Callable

import httpx
from pydantic import BaseModel

from beagle_node.config.schema import NodeConfig

logger = logging.getLogger(__name__)


class _TransientPollError(Exception):
    """Raised when the server returns a transient HTTP error (5xx) or a
    response we cannot parse.  The poll loop catches this and applies
    exponential backoff so a momentary server problem (e.g. uvicorn still
    starting up) does not turn into a hot retry loop on the node."""


# ---------------------------------------------------------------------------
# Bootstrap config schema
# ---------------------------------------------------------------------------

class BootstrapConfig(BaseModel):
    """Minimal per-node config stored locally; everything else comes from server."""
    server_url: str
    """Base URL of the aggregation server, e.g. https://tdoa.example.com"""
    node_id: str
    """Must match the node_id registered on the server via manage_nodes.py"""
    node_secret: str
    """Secret generated by manage_nodes.py add. Never stored on the server in plaintext."""
    config_cache_path: str = "/var/cache/beagle/node_config.json"
    """Path where the last-fetched config is cached for offline startup."""
    config_poll_interval_s: float = 60.0
    """How often to poll for config updates (seconds). Used only as the long-poll
    timeout; the server responds immediately when a new config is available."""
    register_on_start: bool = True
    """Call POST /api/v1/nodes/register on startup to update last_seen_at."""


def load_bootstrap(path: str) -> BootstrapConfig:
    """Load and validate a bootstrap config from a YAML file."""
    import yaml  # type: ignore[import]
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Bootstrap config not found: {p}")
    with p.open() as f:
        raw = yaml.safe_load(f) or {}
    return BootstrapConfig.model_validate(raw)


# ---------------------------------------------------------------------------
# Remote config fetcher
# ---------------------------------------------------------------------------

class RemoteConfigFetcher:
    """
    Fetches NodeConfig from the server, caches it locally, and polls for updates.

    Parameters
    ----------
    bootstrap : BootstrapConfig
        Minimal local config (server URL, node_id, secret).
    """

    def __init__(self, bootstrap: BootstrapConfig) -> None:
        self._bs = bootstrap
        self._headers = {
            "Authorization": f"Bearer {bootstrap.node_secret}",
            "X-Node-ID": bootstrap.node_id,
        }
        self._base = bootstrap.server_url.rstrip("/")
        self._current_version: int = 0
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None
        self._heartbeat_lock = threading.Lock()
        self._heartbeat_data: dict[str, object] = {}
        self._uptime_provider: Callable[[], float] | None = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def fetch_initial_config(self) -> NodeConfig:
        """
        Fetch the node's operating config from the server.

        Falls back to the on-disk cache if the server is unreachable.
        Raises RuntimeError if both the server and cache are unavailable.
        Raises RuntimeError if the server responds with status='pending'
        (admin must call manage_nodes.py set-config).
        """
        config = self._fetch_from_server()
        if config is not None:
            self._save_cache(config)
            return config

        logger.warning(
            "Server unreachable; trying cached config from %s",
            self._bs.config_cache_path,
        )
        config = self._load_cache()
        if config is not None:
            return config

        raise RuntimeError(
            f"Cannot reach server at {self._base} and no cached config found at "
            f"{self._bs.config_cache_path}. "
            "Ensure the server is running and the node is registered "
            "(manage_nodes.py set-config)."
        )

    def start_poll(
        self,
        on_update: Callable[[NodeConfig], None],
        on_restart: Callable[[], None] | None = None,
    ) -> None:
        """
        Start a background thread that long-polls the server for config updates.

        When a new config version is available, ``on_update`` is called with
        the new NodeConfig.

        When the server delivers ``restart_requested: true`` in a poll
        response (set via ``POST /api/v1/nodes/{id}/restart``), ``on_restart``
        is called with no arguments.  The typical implementation calls
        ``os._exit(75)`` so systemd brings the service back up on the
        latest deployed code.  ``on_restart`` is invoked AFTER ``on_update``
        for the same response, so a config update + restart in the same
        poll applies the new config briefly before the process exits.
        Both callbacks run in the background poll thread and should be
        thread-safe.

        Call stop() to terminate the thread.
        """
        if self._thread and self._thread.is_alive():
            return
        self._thread = threading.Thread(
            target=self._poll_loop,
            args=(on_update, on_restart),
            name="remote-config-poll",
            daemon=True,
        )
        self._thread.start()
        logger.info("Remote config poll thread started (version=%d)", self._current_version)

    def stop(self, timeout_s: float = 5.0) -> None:
        """Stop the background poll thread.

        Safe to call from the poll thread itself (e.g. from a config-update
        callback that triggers a restart).  The join is skipped in that case
        to avoid 'cannot join current thread'.
        """
        self._stop_event.set()
        if self._thread and self._thread is not threading.current_thread():
            self._thread.join(timeout=timeout_s)
            self._thread = None

    def set_heartbeat_data(self, data: dict[str, object]) -> None:
        """Update the heartbeat payload sent with each config poll.

        Called from the main SDR loop to feed live telemetry (noise floor,
        thresholds, clock source, etc.) into the config poll request so
        the server receives heartbeat data without a separate POST.
        Thread-safe: the main loop writes, the poll thread reads.
        """
        with self._heartbeat_lock:
            self._heartbeat_data = dict(data)

    def set_uptime_provider(
        self, provider: Callable[[], float] | None,
    ) -> None:
        """Register a callable that returns the node's uptime in seconds.

        The fetcher invokes ``provider()`` once per poll and stamps
        ``uptime_s`` (rounded to 1 decimal) on the heartbeat body sent
        with that poll.  This keeps uptime fresh across the long-poll
        cycle (up to 120 s) without the main loop having to remember to
        update it on every set_heartbeat_data call.

        Pass ``None`` to disable uptime stamping.  The provider may be
        invoked from the poll thread; ``health.HealthMonitor.uptime_s``
        is a safe choice.
        """
        self._uptime_provider = provider

    def _get_heartbeat_data(self) -> dict[str, object]:
        """Snapshot the current heartbeat payload (thread-safe read).

        Stamps a fresh ``uptime_s`` from ``self._uptime_provider`` if one
        is registered, so the server-side heartbeat record always reflects
        the node's true age at the moment the poll was issued (rather
        than the age at last ``set_heartbeat_data`` call).
        """
        with self._heartbeat_lock:
            data = dict(self._heartbeat_data)
        if self._uptime_provider is not None:
            try:
                data["uptime_s"] = round(self._uptime_provider(), 1)
            except Exception as exc:
                logger.warning("uptime_provider raised: %s", exc)
        return data

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _fetch_from_server(self) -> NodeConfig | None:
        """
        Try GET /api/v1/nodes/{node_id}/config.

        Returns a NodeConfig on success, None on network failure, and raises
        RuntimeError if the server responds but the node is pending/rejected.
        """
        url = f"{self._base}/api/v1/nodes/{self._bs.node_id}/config"
        try:
            with httpx.Client(timeout=15.0) as client:
                resp = client.get(url, headers=self._headers)
        except httpx.TransportError as exc:
            logger.warning("Config fetch failed (transport error): %s", exc)
            return None

        if resp.status_code == 304:
            return None  # not modified

        if resp.status_code == 401:
            raise RuntimeError(
                f"Node authentication failed (HTTP 401). "
                "Check that node_id and node_secret in bootstrap.yaml are correct."
            )
        if resp.status_code == 403:
            raise RuntimeError(
                f"Node '{self._bs.node_id}' not found on server (HTTP 403). "
                "Run: manage_nodes.py add <node_id> on the server first."
            )
        if resp.status_code != 200:
            logger.warning("Config fetch returned HTTP %d", resp.status_code)
            return None

        payload = resp.json()
        if payload.get("status") == "pending":
            raise RuntimeError(
                f"Node '{self._bs.node_id}' is registered but has no config assigned yet. "
                "Run: manage_nodes.py set-config <node_id> --config-file <file>"
            )

        config_obj = payload.get("config")
        if not config_obj:
            raise RuntimeError(
                f"Server returned no config for node '{self._bs.node_id}'"
            )

        self._current_version = int(payload.get("config_version", 0))
        try:
            return NodeConfig.model_validate(config_obj)
        except Exception as exc:
            raise RuntimeError(
                f"Server config failed validation: {exc}\n"
                f"Config received: {json.dumps(config_obj, indent=2)}"
            ) from exc

    def _fetch_poll(self, wait_s: int) -> tuple[NodeConfig | None, bool]:
        """
        Long-poll POST /api/v1/nodes/{node_id}/config?wait=N&since_version=V.

        The POST body carries heartbeat telemetry (noise floor, thresholds,
        clock source, location, etc.) so the server receives both a config
        poll and a heartbeat in a single round trip.

        Return values: a 2-tuple ``(new_config, restart_requested)``:
          new_config         - NodeConfig if the server returned a new
                               config, otherwise None
          restart_requested  - True if the server's response carried
                               ``restart_requested: true`` (operator clicked
                               the Restart button); always False on 304

        A 304 / no-change response returns ``(None, False)``.

        Raises:
          httpx.TransportError - network problem; caller backs off
          _TransientPollError  - HTTP 5xx, 4xx, or unparseable response;
                                 caller backs off
        """
        url = (
            f"{self._base}/api/v1/nodes/{self._bs.node_id}/config"
            f"?wait={wait_s}&since_version={self._current_version}"
        )
        hb = self._get_heartbeat_data()
        try:
            with httpx.Client(timeout=float(wait_s) + 5.0) as client:
                resp = client.post(url, json=hb, headers=self._headers)
        except httpx.TransportError as exc:
            logger.warning("Config poll failed (transport error): %s", exc)
            raise

        if resp.status_code == 304:
            return None, False  # no change within wait window

        if 500 <= resp.status_code < 600:
            # Server-side problem (5xx) - probably uvicorn still starting
            # up after a restart, or a transient DB lock.  Back off.
            raise _TransientPollError(
                f"server returned HTTP {resp.status_code}"
            )

        if resp.status_code != 200:
            # 4xx is a client/auth problem - the node_id, secret, or URL
            # is wrong.  Hot-retrying will not fix this; back off so the
            # logs don't fill up while waiting for an operator to notice.
            raise _TransientPollError(
                f"server returned HTTP {resp.status_code}"
            )

        try:
            payload = resp.json()
        except Exception as exc:
            raise _TransientPollError(f"unparseable JSON response: {exc}") from exc

        # Restart instruction is parsed first and returned regardless of
        # whether the same response carries a config update.  A True value
        # is delivered exactly once per ``request_node_restart`` server-side
        # call (see api.py: consume_restart_flag is invoked atomically).
        restart_requested = bool(payload.get("restart_requested"))

        new_version = int(payload.get("config_version", 0))
        if new_version <= self._current_version:
            return None, restart_requested

        config_obj = payload.get("config")
        if not config_obj:
            return None, restart_requested

        try:
            config = NodeConfig.model_validate(config_obj)
        except Exception as exc:
            logger.error("Received invalid config from server: %s", exc)
            return None, restart_requested

        self._current_version = new_version
        return config, restart_requested

    # Backoff parameters (class-level so unit tests can monkeypatch).
    _BACKOFF_INITIAL_S: float = 1.0
    _BACKOFF_MAX_S: float = 120.0
    _BACKOFF_FACTOR: float = 2.0

    def _poll_loop(
        self,
        on_update: Callable[[NodeConfig], None],
        on_restart: Callable[[], None] | None = None,
    ) -> None:
        """Background thread: long-poll for config changes.

        Backoff strategy:
        - Successful poll (new config or no-change/304) resets backoff.
        - Transport error or HTTP 4xx/5xx triggers exponential backoff
          starting at _BACKOFF_INITIAL_S, doubling each consecutive failure
          up to _BACKOFF_MAX_S.  +/-25 percent of jitter is applied each step
          so a fleet of nodes that all started polling against a downed
          server doesn't reconverge into a synchronized retry storm.
        """
        wait_s = max(10, min(int(self._bs.config_poll_interval_s), 120))
        backoff_s = self._BACKOFF_INITIAL_S

        # Initial jitter: stagger nodes so they don't all poll in lockstep
        # after a simultaneous server restart or network recovery.
        self._stop_event.wait(random.uniform(0, min(wait_s, 5)))

        while not self._stop_event.is_set():
            # Add +/-10% jitter to the long-poll wait so nodes desynchronize
            jittered_wait = int(wait_s * random.uniform(0.9, 1.1))
            try:
                new_config, restart_requested = self._fetch_poll(jittered_wait)
            except (httpx.TransportError, _TransientPollError) as exc:
                # Symmetric +/-25% jitter centred on the current backoff so
                # the mean delay matches the nominal exponential schedule.
                jittered_backoff = backoff_s * random.uniform(0.75, 1.25)
                logger.warning(
                    "Config poll error, retrying in %.1fs (backoff=%.1fs): %s",
                    jittered_backoff, backoff_s, exc,
                )
                if self._stop_event.wait(jittered_backoff):
                    return  # stop requested during backoff sleep
                backoff_s = min(backoff_s * self._BACKOFF_FACTOR, self._BACKOFF_MAX_S)
                continue
            except Exception as exc:
                # Anything else (e.g. RuntimeError from terminal auth failure
                # raised inside fetch_initial_config-style codepaths) is logged
                # at error level so it's visible, but we still back off rather
                # than tight-loop.  We never re-raise from a daemon thread.
                jittered_backoff = backoff_s * random.uniform(0.75, 1.25)
                logger.error(
                    "Config poll unexpected error, retrying in %.1fs: %s",
                    jittered_backoff, exc,
                )
                if self._stop_event.wait(jittered_backoff):
                    return
                backoff_s = min(backoff_s * self._BACKOFF_FACTOR, self._BACKOFF_MAX_S)
                continue

            # Reached only on success: reset backoff.  This includes both
            # "new config" and "no change / 304" results -- both indicate the
            # server is healthy.
            if backoff_s != self._BACKOFF_INITIAL_S:
                logger.info("Config poll recovered; resetting backoff")
                backoff_s = self._BACKOFF_INITIAL_S

            if new_config is not None:
                logger.info(
                    "Config update received (version=%d); calling update handler",
                    self._current_version,
                )
                self._save_cache(new_config)
                try:
                    on_update(new_config)
                except Exception as exc:
                    logger.error("Config update callback raised: %s", exc)
            # else: 304 / no change - loop immediately for next long-poll

            # Restart instruction is dispatched AFTER any in-flight config
            # update, so a config-edit-and-restart issued in the same poll
            # response applies the new config briefly before the process
            # exits.  Typical on_restart implementation is os._exit(75);
            # if we return from on_restart without exiting, fall through
            # to the next loop iteration so the node keeps polling.
            if restart_requested:
                logger.warning(
                    "Server requested node restart; invoking on_restart "
                    "callback (process expected to exit).",
                )
                if on_restart is not None:
                    try:
                        on_restart()
                    except Exception as exc:
                        logger.error(
                            "on_restart callback raised: %s", exc,
                        )
                else:
                    logger.error(
                        "Server requested restart but no on_restart "
                        "callback was registered; ignoring.  This is a "
                        "deployment bug -- the node will not restart "
                        "until manually intervened.",
                    )

    def _save_cache(self, config: NodeConfig) -> None:
        """Write the config to the on-disk cache file."""
        p = Path(self._bs.config_cache_path)
        try:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(config.model_dump_json(indent=2))
            logger.debug("Config cached to %s", p)
        except OSError as exc:
            logger.warning("Could not write config cache to %s: %s", p, exc)

    def _load_cache(self) -> NodeConfig | None:
        """Load a previously cached config from disk."""
        p = Path(self._bs.config_cache_path)
        if not p.exists():
            return None
        try:
            text = p.read_text()
            config = NodeConfig.model_validate_json(text)
            logger.info("Loaded cached config from %s", p)
            return config
        except Exception as exc:
            logger.warning("Could not load cached config from %s: %s", p, exc)
            return None
